Support qos_options in data source
nttcom/terraform-provider-ecl pull request #76
Opened 2020-12-22 07:50 UTC by ak1ra24

This PR adds qos_options data_source.

2021-02-03 10:39 UTC, yuuki0311 reviewed
PRありがとうございます。
確認してみた所、テストのコードに何点か修正頂きたい箇所がございましたので、指摘をあげさせて頂きました。
お手数お掛けしますが、ご確認の程、よろしくお願い致します。

2021-02-03 10:39 UTC, yuuki0311 commented on ecl/data_source_ecl_network_qos_options_v2_mock_test.go
> +        - 20M-GA-AZURE
実在するQOSオプションを指定して頂きたいので`10Mbps-BestEffort`をご利用頂けたらと思います。
```suggestion
        - 10Mbps-BestEffort
```

2021-02-03 10:39 UTC, yuuki0311 commented on ecl/data_source_ecl_network_qos_options_v2_mock_test.go
> +						"data.ecl_network_qos_options_v2.qos_options_1", "name", "20M-GA-AZURE"),
実在するQOSオプションを指定して頂きたいので`10Mbps-BestEffort`をご利用頂けたらと思います。
```suggestion
						"data.ecl_network_qos_options_v2.qos_options_1", "name", "10Mbps-BestEffort"),
```

2021-02-03 10:39 UTC, yuuki0311 commented on ecl/data_source_ecl_network_qos_options_v2_test.go
> +						"data.ecl_network_qos_options_v2.qos_options_1", "name", "20M-GA-AZURE"),
実在するQOSオプションを指定して頂きたいので`10Mbps-BestEffort`をご利用頂けたらと思います。
```suggestion
						"data.ecl_network_qos_options_v2.qos_options_1", "name", "10Mbps-BestEffort"),
```

2021-03-01 08:24 UTC, yuuki0311 commented
修正ありがとうございます 🙇 確認しました。
しかし二点、再修正をお願いしたい箇所がありますので、残りの指摘と併せてご対応を宜しくお願い致します。

どちらも、MockのResponseについての指摘となります。
１．【body : > 】⇒【body : |】に変わっていますが、他のMockと統一する為に元に戻して頂けると幸いです。
２．Response Bodyのインデントは正しく行ってください。

2021-03-03 07:43 UTC, yuuki0311 commented on ecl/data_source_ecl_network_qos_options_v2_test.go
> +			},
当指摘の対応がまだのようですので、よろしくお願いします。

2021-03-05 00:43 UTC, ysssasaki requested changes
追加でコメントしましたので、修正お願いいたします 🙇

2021-03-05 00:43 UTC, ysssasaki commented on website/docs/d/network_qos_options_v2.html.markdown
> +* `qos_options_id` - (Optional) Unique ID of the Qos option.
```suggestion
* `qos_option_id` - (Optional) Unique ID of the Qos option.
```

2021-03-05 00:43 UTC, ysssasaki commented on ecl/data_source_ecl_network_qos_options_v2_test.go
> +  qos_options_id = "${data.ecl_network_qos_options_v2.qos_options_1.id}"
```suggestion
  qos_option_id = "${data.ecl_network_qos_options_v2.qos_options_1.id}"
```

2021-03-05 00:43 UTC, ysssasaki commented on ecl/data_source_ecl_network_qos_options_v2_test.go
> +			},
```suggestion
```
descriptionのテストはmockテストには残して、通常のテストから削除してください

2021-03-05 00:43 UTC, ysssasaki commented on ecl/data_source_ecl_network_qos_options_v2_mock_test.go
> +		},
```suggestion
		},
		resource.TestStep{
			Config: testAccNetworkV2QosOptionsDataSourceDescription,
			Check: resource.ComposeTestCheckFunc(
				testAccCheckNetworkV2QosOptionsDataSourceID("data.ecl_network_qos_options_v2.qos_options_1"),
			),
		},
```
descriptionのテストはmockテストには残して、通常のテストから削除してください

2021-03-05 00:43 UTC, ysssasaki commented on website/docs/d/network_qos_options_v2.html.markdown
> +	name = "20M-GA-AZURE"
```suggestion
	name = "10Mbps-BestEffort"
```

2021-03-05 05:10 UTC, yuuki0311 approved these changes

2021-03-08 00:53 UTC, ysssasaki requested changes
2箇所指摘漏れをしておりました。
追加の修正お願いいたします 🙇

2021-03-08 00:53 UTC, ysssasaki commented on ecl/data_source_ecl_network_qos_options_v2_mock_test.go
> +        - "10m-besteffort-menu"
```suggestion
        - "10M-besteffort-menu"
```

2021-03-08 00:53 UTC, ysssasaki commented on ecl/data_source_ecl_network_qos_options_v2_mock_test.go
> +                    "description": "10m-besteffort-menu",
```suggestion
                    "description": "10M-besteffort-menu",
```

2021-03-09 00:16 UTC, ysssasaki approved these changes
修正ありがとうございました 🙇 
LGTM 🍊

2021-03-09 00:16 UTC, merged