:bug: IF-5481 Fixed How to Get Tenant ID from OS_TENANT_ID
nttcom/terraform-provider-ecl pull request #88
Opened 2022-03-30 07:35 UTC by sugimo-s

2022-03-31 02:05 UTC, ysssasaki requested changes

2022-03-31 02:05 UTC, ysssasaki commented on ecl/resource_ecl_security_network_based_device_ha_v2_test.go
> +		found1, err := getHADeviceByHostName(client, id1, os.Getenv("OS_TENANT_ID"))
既存のテストコードに関しても、環境変数に依存する箇所は減らしておいたほうが良いかと思いました。
ここのテナントIDはconfig.TenantID などで与えることは出来ないでしょうか？
他の箇所も同様です。

2022-03-31 06:14 UTC, sugimo-s commented on ecl/resource_ecl_security_network_based_device_ha_v2_test.go
> +		found1, err := getHADeviceByHostName(client, id1, os.Getenv("OS_TENANT_ID"))
結論としては、できません。
terraform本体が tfファイルを読みこんで、 `ResourceData` や `Config` のインスタンスを生成します。
terraform-provider-eclは terraform本体から呼ばれるときに引数として `ResourceData` や `Config` を渡されるため、ここからテナントIDを参照することができます。
テストコードは terraformを呼ぶ処理（terraformの外部にある処理）のため、 `ResourceData` や `Config` を利用できません。

2022-03-31 07:09 UTC, ysssasaki commented on ecl/resource_ecl_security_network_based_device_ha_v2_test.go
> +		found1, err := getHADeviceByHostName(client, id1, os.Getenv("OS_TENANT_ID"))
試しに私の環境でモックテストを動かしてみましたが、configからテナントIDを取得できるように見えました。（また、テストもパスしました）
ご確認いただけますでしょうか 🙇 
![Screen Shot 2022-03-31 at 16 05 05](https://user-images.githubusercontent.com/64194789/160997576-4f3b5d14-48aa-4272-a7f0-b225c3f4a355.png)

2022-03-31 08:07 UTC, sugimo-s commented on ecl/resource_ecl_security_network_based_device_ha_v2_test.go
> +		found1, err := getHADeviceByHostName(client, id1, os.Getenv("OS_TENANT_ID"))
失礼しました。テスト時は `Provider` インスタンスを作成しているため、そこから `Config` を取得できると理解しました。
★その上でご提案ですが、 `os.Getenv("OS_TENANT_ID")` でも `config.TenantID` でもなく、 `OS_TENANT_ID` を利用してはいかがでしょうか。
`OS_TENANT_ID` は [provider_test.go#L36](https://github.com/nttcom/terraform-provider-ecl/blob/master/ecl/provider_test.go#L36) にて環境変数OS_TENANT_IDの値を格納したものです。
たとえば [resource_ecl_security_network_based_device_ha_v2_test.go#L410](https://github.com/nttcom/terraform-provider-ecl/blob/master/ecl/resource_ecl_security_network_based_device_ha_v2_test.go#L410) を確認いただくとわかりますが、tfファイルの resourceに相当する箇所には `OS_TENANT_ID` の値を利用しています。
Getenvメソッドを毎回実行する必然性はないため、 `os.Getenv("OS_TENANT_ID")` よりは `OS_TENANT_ID` が良いと思います。
`config.TenantID` は（今回の改修箇所はたまたま事前に configを取得しているようですが）事前に configを取得する処理が必要になり冗長です。

2022-03-31 08:19 UTC, ysssasaki commented on ecl/resource_ecl_security_network_based_device_ha_v2_test.go
> +		found1, err := getHADeviceByHostName(client, id1, os.Getenv("OS_TENANT_ID"))
`OS_TENANT_ID`を使う方針で良いかと思います 🙇

2022-04-04 08:03 UTC, ysssasaki approved these changes

2022-04-05 00:17 UTC, NaoShark approved these changes

2022-04-05 04:14 UTC, merged