IF-7466 fix examples based on results of terraform fmt
nttcom/terraform-provider-ecl pull request #92
Opened 2022-04-08 02:08 UTC by shuhei14

2022-04-08 05:16 UTC, NaoShark requested changes

2022-04-08 05:16 UTC, NaoShark commented on examples/app-with-networking-and-storage/compute.tf
>      port = "${ecl_network_port_v2.port_1_1.id}"
```suggestion
    port = ecl_network_port_v2.port_1_1.id
```

2022-04-08 05:16 UTC, NaoShark commented on examples/app-with-networking-and-storage/compute.tf
>      port = "${ecl_network_port_v2.port_1_2.id}"
```suggestion
    port = ecl_network_port_v2.port_1_2.id
```

2022-04-08 05:16 UTC, NaoShark commented on examples/app-with-networking-and-storage/network.tf
>      subnet_id  = "${ecl_network_subnet_v2.subnet_1_1.id}"
```suggestion
    subnet_id  = ecl_network_subnet_v2.subnet_1_1.id
```

2022-04-08 05:16 UTC, NaoShark commented on examples/app-with-networking-and-storage/network.tf
>      subnet_id  = "${ecl_network_subnet_v2.subnet_1_2.id}"
```suggestion
    subnet_id  = ecl_network_subnet_v2.subnet_1_2.id
```

2022-04-08 06:32 UTC, NaoShark approved these changes

2022-04-11 05:12 UTC, ysssasaki approved these changes

2022-04-11 05:17 UTC, merged