IF-5692 add format check by github actions
nttcom/terraform-provider-ecl pull request #93
Opened 2022-04-12 01:25 UTC by shuhei14

2022-04-14 08:34 UTC, ManabuMiwa approved these changes

2022-04-18 01:06 UTC, kazyshr commented on .github/workflows/test.yml
> +        terraform-version: [0.12.x]
0.12よりも新しいバージョンが出ているようなので、matrixに追加いただけますか？

2022-04-18 01:06 UTC, kazyshr commented on .github/workflows/test.yml
> +        terraform-version: [0.12.x]
0.12よりも新しいバージョンが出ているようなので、matrixに追加いただけますか？

2022-04-18 01:12 UTC, kazyshr commented on .github/workflows/test.yml
> +        run: if [ "$(gofmt -l `find . -name '*.go' | grep -v vendor` | wc -l)" -gt 0 ]; then exit 1; fi
vendorディレクトリを明示的に除外するのは必要でしょうか？
> grep -v vendor

以下の箇所はドット(.)だけではだめなのでしょうか？
> find . -name '*.go'

2022-04-18 01:12 UTC, kazyshr commented on .github/workflows/test.yml
> +        run: if [ "$(gofmt -l `find . -name '*.go' | grep -v vendor` | wc -l)" -gt 0 ]; then exit 1; fi
vendorディレクトリを明示的に除外するのは必要でしょうか？
> grep -v vendor

以下の箇所はドット(.)だけではだめなのでしょうか？
> find . -name '*.go'

2022-04-18 01:15 UTC, kazyshr commented on .github/workflows/test.yml
> +        run: go test `go list ./... | grep -v 'vendor'`
以下ではだめでしょうか？
```suggestion
        run: go test ./...
```
```suggestion
        run: go test `go list ./... | grep -v 'vendor'`
```

2022-04-18 01:16 UTC, kazyshr requested changes
インラインでコメントしました。

2022-04-19 02:25 UTC, kazyshr reviewed
追加でコメントしました。

2022-04-19 02:25 UTC, kazyshr commented on .github/workflows/test.yml
> +        run: if [ "$(gofmt -l . | grep -v vendor | wc -l)" -gt 0 ]; then exit 1; fi
grep -v vendor が必要ならば、前半部分も変更しないほうが良いのではないでしょうか？
変更後のコードだとvendor配下のファイルについてもgofmtが働いてしまう気がします。
```suggestion
        run: if [ "$(gofmt -l `find . -name '*.go' | grep -v vendor` | wc -l)" -gt 0 ]; then exit 1; fi
```

2022-04-19 02:32 UTC, shuhei14 commented on .github/workflows/test.yml
> +        run: if [ "$(gofmt -l . | grep -v vendor | wc -l)" -gt 0 ]; then exit 1; fi
失礼致しました。
ご指摘して頂いた通りなので修正致しました。

2022-04-20 01:11 UTC, kazyshr approved these changes

2022-04-20 01:36 UTC, merged