Support VNA plan
nttcom/terraform-provider-ecl pull request #94
Opened 2022-04-21 18:09 UTC by kajiuray

This is a commit corresponding to [eclcloud#38](https://github.com/nttcom/eclcloud/pull/38).
The user will be able to create a VNA by indicating some of plan's attribute like `id` and `name`.

This PR includes follows.
- Add `ecl_vna_appliance_plan_v1` data type
- Add a related document
- Add tests

Ref:
https://sdpf.ntt.com/services/docs/firewall/api-references/rsts/APIList/source/list_virtual_network_appliance_plan.html

2022-04-22 07:18 UTC, sugimo-s approved these changes

2022-04-26 05:57 UTC, ysssasaki requested changes
I commented on the Mock test.
I will also comment on regular tests later 🙇

2022-04-26 05:57 UTC, ysssasaki commented on ecl/data_source_ecl_vna_appliance_plan_v1_mock_test.go
> +				Config: testAccVNAV1AppliancePlanDataSourceBasic,
```suggestion
				Config: testAccVNAV1AppliancePlanDataSourceQueryName,
```

2022-04-26 05:57 UTC, ysssasaki commented on ecl/data_source_ecl_vna_appliance_plan_v1_mock_test.go
> +					testAccCheckVNAV1AppliancePlanDataSourceID("data.ecl_vna_appliance_plan_v1.appliance_plan_1"),
```suggestion
					testAccCheckVNAV1AppliancePlanDataSourceID("data.ecl_vna_appliance_plan_v1.appliance_plan_2"),
```

2022-04-26 05:57 UTC, ysssasaki commented on ecl/data_source_ecl_vna_appliance_plan_v1_mock_test.go
> +				),
```suggestion
					resource.TestCheckResourceAttr(
						"data.ecl_vna_appliance_plan_v1.appliance_plan_1", "description", testAccVNAV1AppliancePlanDataSourcePlanName),
				),
```

2022-04-26 05:57 UTC, ysssasaki commented on ecl/data_source_ecl_vna_appliance_plan_v1_mock_test.go
> +        - virtual_network_appliance_plans_description
```suggestion
      description:
        - %q
```

2022-04-26 05:57 UTC, ysssasaki commented on ecl/data_source_ecl_vna_appliance_plan_v1_mock_test.go
> +              "description": "virtual_network_appliance_plans_description",
```suggestion
              "description": %q,
```

2022-04-26 05:57 UTC, ysssasaki commented on ecl/data_source_ecl_vna_appliance_plan_v1_mock_test.go
> +`, testAccVNAV1AppliancePlanDataSourcePlanName,
```suggestion
`, testAccVNAV1AppliancePlanDataSourcePlanName, testAccVNAV1AppliancePlanDataSourcePlanName, testAccVNAV1AppliancePlanDataSourcePlanName,
```

2022-04-27 01:14 UTC, ysssasaki requested changes

2022-04-27 01:14 UTC, ysssasaki commented on ecl/data_source_ecl_vna_appliance_plan_v1_test.go
> +						"data.ecl_vna_appliance_plan_v1.appliance_plan_1", "flavor", "2CPU-8GB"),
```suggestion
						"data.ecl_vna_appliance_plan_v1.appliance_plan_1", "flavor", "2CPU-4GB"),
```

2022-04-27 01:14 UTC, ysssasaki commented on ecl/data_source_ecl_vna_appliance_plan_v1_test.go
> +						"data.ecl_vna_appliance_plan_v1.appliance_plan_1", "availability_zones.#", "1"),
```suggestion
						"data.ecl_vna_appliance_plan_v1.appliance_plan_1", "availability_zones.#", "3"),
```
The value of lab3 is 3.

2022-04-27 01:14 UTC, ysssasaki commented on ecl/data_source_ecl_vna_appliance_plan_v1_test.go
> +  flavor = "2CPU-8GB"
```suggestion
  flavor = "2CPU-4GB"
```

2022-04-27 01:14 UTC, ysssasaki commented on ecl/data_source_ecl_vna_appliance_plan_v1_test.go
> +  id = "${data.ecl_network_appliance_plan_v1.appliance_plan_1.id}"
```suggestion
  id = "${data.ecl_vna_appliance_plan_v1.appliance_plan_1.id}"
```

2022-04-27 01:14 UTC, ysssasaki commented on ecl/data_source_ecl_vna_appliance_plan_v1.go
> +	}
```suggestion
	licenses := make([]map[string]string, len(plan.Licenses))
	for i, l := range plan.Licenses {
		license := map[string]string{"license_type": l.LicenseType}
		licenses[i] = license
	}
```
The list length is specified at the time of initialization, the length will be doubled when append.

2022-04-27 01:14 UTC, ysssasaki commented on ecl/data_source_ecl_vna_appliance_plan_v1.go
> +	}
```suggestion
	for i, az := range plan.AvailabilityZones {
		availability_zone := make(map[string]interface{})
		availability_zone["availability_zone"] = az.AvailabilityZone
		availability_zone["available"] = az.Available
		availability_zone["rank"] = az.Rank
		availability_zones[i] = availability_zone
	}
```

2022-04-27 01:27 UTC, ysssasaki approved these changes

2022-04-27 01:29 UTC, merged